### ISSUE TITLE
Schema has changed in SanityEpisode, no key named `image`

### ISSUE THREAD

**Issue by weeshinwang** [jlengstorf/frontend-masters-intro-to-gatsby-project#9]
In the section 'Use Third-Party Data', we dymanically create pages based on GraphQL queries from Sanity CMS.
But there is no key named `image` in the SanityEpisode schema, using the query instructed as below will result in error.

```js
export const query = graphql`
  query SanityEpisode($id: String!) {
    sanityEpisode(id: { eq: $id }) {
      title
      description
      slug {
        current
      }
      youtubeID
      date(fromNow: true)
      image {
        asset {
          gatsbyImageData(placeholder: DOMINANT_COLOR)
        }
      }
    }
  }
`;
```

**Comment by bhaveek424** [comment]
I'm facing the same issue. `image` key is not there in graphql query along with `gatsbyPath`

**Comment by jlengstorf** [comment]
Hey, y'all! Sorry about that. I've added the `image` field back to the schema and it will work now.
